//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backendMargarita.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tareas
    {
        public int id { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public string descripcion { get; set; }
        public bool estado { get; set; }
        public System.DateTime fechaVencimiento { get; set; }
        public int idUsuario { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
